seed = "42"                         # RNG seed, use "" for no seeding
n = "1000"                          # number of agents
R = "0.2"                           # edges correlation matrix
layer_params = "layer_params.csv"   # file with parameters for each layer
d_max_iter = "1000"                 # maximum number of iterations for sampling degrees
c_max_iter = "1000"                 # maximum number of iterations for sampling cluster sizes
t = "1000"                          # number of batches for edge rewiring
e = "0.1"                           # percent of edges to be rewired in each rewiring batch