name: Documentation

on:
  push:
    branches:
      - documentation
  #   tags: '*'
  # pull_request:

jobs:
  build:
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Julia Setup
        uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - name: Julia Cache
        uses: julia-actions/cache@v2
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.add(url="https://github.com/bkamins/ABCDGraphGenerator.jl"); Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs/ --code-coverage=user docs/make.jl
      - name: Code coverage
        run: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'